<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

<xacro:property name="base_radii" value="0.100"/>
<!-- height from the ground to the top of the base plate -->
<xacro:property name="base_height" value="0.180"/> 
<xacro:property name="base_plate_thickness" value="0.010"/> 
<xacro:property name="base_plate_radii" value="0.070"/> 
<xacro:property name="base_plate_distance" value="0.010"/> 

<!-- arm1 joint height from the base plate -->
<xacro:property name="arm1_joint_height" value="0.060"/> 
<xacro:property name="arm1_width" value="0.040"/> 
<!-- arm2 joint height from the joint1 -->
<xacro:property name="arm2_joint_height" value="0.400"/> 
<xacro:property name="arm2_width" value="0.040"/> 

<xacro:property name="end_effector_joint_height" value="0.350"/> 
<xacro:property name="end_effector_joint_offset" value="0.050"/> 

<xacro:property name="arm1_length" value="${arm2_joint_height - arm1_width * 1.5 / 2}"/> 
<xacro:property name="arm2_length" value="${end_effector_joint_height}"/> 

<!-- Mass Properties -->
<xacro:property name="supp_link_mass" value="1.5"/>
<xacro:property name="base_link_mass" value="5.0"/>
<xacro:property name="base_plate_mass" value="1.0"/>
<xacro:property name="arm1_mass" value="0.5"/>
<xacro:property name="arm2_mass" value="0.5"/>
<xacro:property name="ef_holder_mass" value="0.1"/>
<xacro:property name="gripper_mass" value="0.05"/>
<xacro:property name="end_effector_mass" value="0.001"/>

  <xacro:macro name="Supp_Link" params="parent x y z height">
    <link name="supp_link${parent}">
      <visual>
        <origin xyz="0 0 0" rpy="-1.57 0 0"/>
        <geometry>
          <cylinder radius="0.04" length="${height}"/>
        </geometry>
        <material name="blue"/>
      </visual>
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="${supp_link_mass}" />
        <inertia ixx="${(supp_link_mass/12) * (3*0.04*0.04 + height*height)}" 
                 ixy="0" ixz="0"
                 iyy="${(supp_link_mass/12) * (3*0.04*0.04 + height*height)}" 
                 iyz="0"
                 izz="${(supp_link_mass * 0.04*0.04)/2}" />
      </inertial>
    </link>
    <joint name="supp_joint${parent}" type="fixed">
      <parent link="${parent}"/>
      <child link="supp_link${parent}"/>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

  <!-- Base_Link -->
  <link name="base_link">
    <visual>
      <origin xyz="0.0 0.0 ${base_height/2 - base_plate_thickness/2 - base_plate_distance/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${base_radii}" length="${base_height - base_plate_thickness - base_plate_distance}"/>
      </geometry>
      <material name="grey"/>
    </visual>

    <collision>
      <origin xyz="0.0 0.0 ${base_height/2 - base_plate_thickness/2 - base_plate_distance/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${base_radii}" length="${base_height - base_plate_thickness - base_plate_distance}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="${base_link_mass}" />
      <inertia ixx="${(base_link_mass/12) * (3*base_radii*base_radii + base_height*base_height)}" 
               ixy="0" ixz="0"
               iyy="${(base_link_mass/12) * (3*base_radii*base_radii + base_height*base_height)}" 
               iyz="0"
               izz="${(base_link_mass * base_radii*base_radii)/2}" />
    </inertial>
  </link>

  <!-- Dummy_Link -->
  <link name="dummy_link">
    <visual>
      <origin xyz="0.0 0.0 ${base_height/2 + arm1_joint_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.030" length="${base_height + arm1_joint_height}"/>
      </geometry>
      <material name="grey"/>
    </visual>
  </link>
  <!-- Dummy_Joint -->
  <joint name="dummy_joint" type="fixed">
    <parent link="base_link"/>
    <child link="dummy_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>


  <!-- Base_Link_Plate_Joint -->
  <joint name="base_link_plate_joint" type="revolute">
    <parent link="base_link"/>
    <child link="base_plate"/>
    <origin xyz="0.0 0.0 ${base_height}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit velocity="10" effort="20" lower="${-pi*0.9}" upper="${pi*0.9}"/> 
  </joint>

  <!--  Base_Plate -->
  <link name="base_plate">
    <visual>
      <origin xyz="0 0 ${-base_plate_thickness/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${base_plate_radii}" length="${base_plate_thickness}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${-base_plate_thickness/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${base_plate_radii}" length="${base_plate_thickness}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="${base_plate_mass}" />
      <inertia ixx="${(base_plate_mass/12) * (3*base_plate_radii*base_plate_radii + base_plate_thickness*base_plate_thickness)}" 
               ixy="0" ixz="0"
               iyy="${(base_plate_mass/12) * (3*base_plate_radii*base_plate_radii + base_plate_thickness*base_plate_thickness)}" 
               iyz="0"
               izz="${(base_plate_mass * base_plate_radii*base_plate_radii)/2}" />
    </inertial>
  </link>

  <!--  Base_Plate_Arm1_Joint -->
  <joint name="base_plate_arm1_joint" type="revolute">
    <parent link="base_plate"/>
    <child link="arm1"/>
    <origin xyz="0.0 0.0 0.060" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit velocity="1000" effort="10000" lower="${-pi * 0.9 / 2}" upper="${pi * 0.9 / 2}" />
  </joint>

  <xacro:Supp_Link parent="arm1" x="0" y="0" z="0.0" height="0.060"/>

  <!--  Arm1 -->
  <link name="arm1">
    <visual>
      <origin xyz="0 0 ${arm1_length/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${arm1_width} ${arm1_width} ${arm1_length}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${arm1_length/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${arm1_width} ${arm1_width} ${arm1_length}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 ${arm1_length/2}" />
      <mass value="${arm1_mass}" />
      <inertia ixx="${(arm1_mass/12) * (arm1_width*arm1_width + arm1_length*arm1_length)}" 
               ixy="0" ixz="0"
               iyy="${(arm1_mass/12) * (arm1_width*arm1_width + arm1_length*arm1_length)}" 
               iyz="0"
               izz="${(arm1_mass/12) * (arm1_width*arm1_width + arm1_width*arm1_width)}" />
    </inertial>
  </link>

  <!--  Base_Plate_Arm2_Joint -->
  <joint name="arm1_arm2_joint" type="revolute">
    <parent link="arm1"/>
    <child link="arm2"/>
    <origin xyz="0.0 0.045 ${arm2_joint_height}" rpy="0 1.57 0"/>
    <axis xyz="0 1 0"/>
    <limit velocity="10" effort="20" lower="${-pi * 0.8 / 2}" upper="${pi * 0.8 / 2}" />
  </joint>

  <xacro:Supp_Link parent="arm2" x="0" y="-0.025" z="0" height="0.100"/>

  <!--  Arm2 -->
  <link name="arm2">
    <visual>
      <origin xyz="0 0 ${arm2_length/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${arm2_width} ${arm2_width} ${arm2_length}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${arm2_length/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${arm2_width} ${arm2_width} ${arm2_length}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 ${arm2_length/2}" />
      <mass value="${arm2_mass}" />
      <inertia ixx="${(arm2_mass/12) * (arm2_width*arm2_width + arm2_length*arm2_length)}" 
               ixy="0" ixz="0"
               iyy="${(arm2_mass/12) * (arm2_width*arm2_width + arm2_length*arm2_length)}" 
               iyz="0"
               izz="${(arm2_mass/12) * (arm2_width*arm2_width + arm2_width*arm2_width)}" />
    </inertial>
  </link>

  <!--  EF_Holder_Joint -->
  <joint name="ef_holder_joint" type="fixed">
    <parent link="arm2"/>
    <child link="ef_holder_link"/>
    <origin xyz="0.0 0.0 ${end_effector_joint_height - 0.010}" rpy="0 -1.57 0"/>
  </joint>

  <!--  EF_Holder_Link -->
  <link name="ef_holder_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find proxygen_description)/meshes/chain_link5.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="grey"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find proxygen_description)/meshes/chain_link5.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="${ef_holder_mass}" />
      <inertia ixx="1.0e-03" ixy="0.0" ixz="0.0"
               iyy="1.0e-03" iyz="0.0"
               izz="1.0e-03" />
    </inertial>
  </link>

  <!--  Gripper link -->
  <link name="gripper_link">
    <visual>
      <origin xyz="0.0 0.0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find proxygen_description)/meshes/chain_link_grip_l.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="grey"/>
    </visual>

    <collision>
      <origin xyz="0.0 0.0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find proxygen_description)/meshes/chain_link_grip_l.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="${gripper_mass}" />
      <inertia ixx="1.0e-03" ixy="0.0" ixz="0.0"
               iyy="1.0e-03" iyz="0.0"
               izz="1.0e-03" />
    </inertial>
  </link>

  <!--  Gripper joint -->
  <joint name="gripper" type="prismatic">
    <parent link="ef_holder_link"/>
    <child link="gripper_link"/>
    <origin xyz="0.0817 0.021 0.0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit velocity="10" effort="20" lower="-0.010" upper="0.019" />
  </joint>

  <!--  Gripper link sub -->
  <link name="gripper_link_sub">
    <visual>
      <origin xyz="0.0 -0.0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find proxygen_description)/meshes/chain_link_grip_r.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="grey"/>
    </visual>

    <collision>
      <origin xyz="0.0 -0.0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find proxygen_description)/meshes/chain_link_grip_r.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="${gripper_mass}" />
      <inertia ixx="1.0e-03" ixy="0.0" ixz="0.0"
               iyy="1.0e-03" iyz="0.0"
               izz="1.0e-03" />
    </inertial>
  </link>

  <!--  Gripper joint sub -->
  <joint name="gripper_sub" type="prismatic">
    <parent link="ef_holder_link"/>
    <child link="gripper_link_sub"/>
    <origin xyz="0.0817 -0.021 0" rpy="0 0 0"/>
    <axis xyz="0 -1 0"/>
    <limit velocity="10" effort="20" lower="-0.010" upper="0.019" />
    <!-- <mimic joint="gripper" multiplier="1"/> -->
  </joint>


  <!-- end effector joint -->
  <joint name="end_effector_joint" type="continuous">
    <origin xyz="0.126 0.0 0.0" rpy="0 0 0"/>
    <parent link="ef_holder_link"/>
    <child link="end_effector_link"/>
    <axis xyz="1 0 0"/>
    <limit velocity="1" effort="0.1" />
  </joint>

  <!-- end effector link -->
  <link name="end_effector_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
      <material name="red"/>
     </visual>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="${end_effector_mass}" />
      <inertia ixx="1.0e-03" ixy="0.0" ixz="0.0"
               iyy="1.0e-03" iyz="0.0"
               izz="1.0e-03" />
    </inertial>
  </link>

  
</robot>



